version: '3.4'

services:
  app:
    env_file:
      - .env
    container_name: ${APP_NAME}-api
    build:
      context: .
    entrypoint: "/usr/src/app/run/entrypoint.dev.sh"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
